{% set name = "eeharvest" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/eeharvest-{{ version }}.tar.gz
  sha256: be2914df86ef856d9b1e689cc43e9a680474d6d94281bd3a66c850b653927da2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools-scm
    - pip
  run:
    - python >=3.8
    - importlib-metadata
    - importlib-resources
    - alive-progress
    - earthengine-api
    - eemont
    - geedim
    - geemap
    - pyyaml
    - termcolor
    - yamale

test:
  imports:
    - eeharvest
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sydney-informatics-hub/eeharvest
  summary: An automated, convenient downloader for Google Earth Engine datasets in Python
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - januarharianto
