{% set name = "eeharvest" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/eeharvest-{{ version }}.tar.gz
  sha256: 14194d3508b39121799f08e028113a0547b4e34abadce5d70323f39bd94298f9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - importlib-metadata
    - importlib-resources
    - alive-progress
    - earthengine-api
    - eemont
    - geedim
    - geemap
    - numpy
    - pyyaml
    - termcolor
    - tqdm
    - yamale

test:
  imports:
    - eeharvest
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sydney-informatics-hub/eeharvest
  summary: An automated, convenient downloader for Google Earth Engine datasets in Python
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - januarharianto
